name: querydsl

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - README.md

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Initialize cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: build
        run: mvn --batch-mode clean install -DskipTests

      - uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: .

  test:
    needs: build
    strategy:
      matrix:
        target: [unit-test]
#          target: [unit-test, integration tests, db2, derby, h2, hsqldb, sqlite, mysql, postgresql, mongodb, firebird,
#                   cubrid, teradata, sqlserver, oracle, hibernate5, benchmark, performance, slow-tests, reporting]
        include:
          - target: unit-test
            containers: null
            maven-args: test

#            - target: db2
#              containers: db2
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.DB2 -DskipUTs
#
#            - target: derby
#              containers: derby
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.Derby -DskipUTs
#
#            - target: h2
#              containers: null
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.H2 -DskipUTs
#
#            - target: hsqldb
#              containers: hsqldb
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.HSQLDB -DskipUTs
#
#            - target: sqlite
#              containers: sqlite
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.SQLite -DskipUTs
#
#            - target: mysql
#              containers: mysql
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.MySQL -DskipUTs
#
#            - target: postgresql
#              containers: postgresql
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.PostgreSQL -DskipUTs
#
#            - target: mongodb
#              containers: mongodb
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.MongoDB -DskipUTs
#
#            - target: firebird
#              containers: firebird
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.Firebird -DskipUTs
#
#            - target: cubrid
#              containers: cubrid
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.CUBRID -DskipUTs
#
#            - target: teradata
#              containers: teradata
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.teradata -DskipUTs
#
#            - target: sqlserver
#              containers: sqlserver
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.sqlserver -DskipUTs
#
#            - target: oracle
#              containers: oracle
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.oracle -DskipUTs
#
#            - target: hibernate5
#              containers: null
#              maven-args: verify --activate-profiles jpa,hibernate5,travis,examples --projects !querydsl-jpa-codegen
#
#            - target: benchmark
#              containers: null
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.Benchmark -DskipUTs
#
#            - target: performance
#              containers: null
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.Performance -DskipUTs
#
#            - target: slow-tests
#              containers: null
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.SlowTest -DskipUTs
#
#            - target: reporting
#              containers: null
#              maven-args: verify -DincludedGroups=com.querydsl.core.testutil.ReportingOnly -DskipUTs

    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v1
        with:
          name: workspace

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Start test databases
        if: ${{ matrix.containers }}
        run: docker-compose --file travis/docker-compose.yml up --detach ${matrix.containers}

      - name: Initialize cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run tests
        run: mvn --batch-mode install -am jacoco:report ${{ matrix.maven-args }}

      - name: Report coverage
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn --batch-mode coveralls:report

      - name: Deploy snapshot 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: mvn --batch-mode deploy --settings deploy/.m2/settings.xml -DskipTests

      - name: Clean up before caching
        run: rm -rf ~/.m2/repository/com/querydsl/
